"""Shared machinery for trajan tables.

This module holds the pieces that are (or will be) common across the three
tiers — SynapseTable, EdgeList, ConnectivityTable — so that each tier can
compose them rather than reimplement them:

- Annotation-spec dataclasses: one per annotation kind. Replaces the ad-hoc
  tuple storage originally used on SynapseTable. The ``lf`` attribute is
  first on every spec so the existing ``_AnnotationProxy`` can continue to
  access the underlying LazyFrame uniformly.
- ``BlessedColumns``: a small dataclass holding the role → concrete-column
  mappings and the weight-column list. Centralizes the "semantic columns the
  library interprets" concept from the blessed-columns memory.
- Low-level input-coercion helpers (``_to_lazy``, ``_auto_pack``) that every
  tier needs when accepting user frames / positions.

This file intentionally stays small and free-standing. The real base class
(``_TrajanTable`` with filter / expression / cache machinery) is deferred
until the second and third tiers are implemented, so the shared surface can
be factored from observed duplication rather than speculated in advance.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Union

import polars as pl

from .spatial import pack_position

try:
    import pandas as pd

    _HAS_PANDAS = True
except ImportError:
    _HAS_PANDAS = False


# ── annotation-spec dataclasses ───────────────────────────────────────────────


@dataclass
class SynapseAnnotationSpec:
    """Synapse-level annotation: keyed on synapse id.

    Joined onto the base synapse lazy plan via the table's ``id_col``.
    Contributes ``data_cols`` verbatim to ``.df``.
    """

    lf: pl.LazyFrame
    data_cols: list[str]


@dataclass
class CellAnnotationSpec:
    """Cell-level annotation: keyed on cell id (or on an alias column).

    Joined symmetrically for pre and post cells; each ``data_col`` produces
    ``{col}_pre`` and ``{col}_post`` columns on ``.df``.

    Parameters
    ----------
    lf : pl.LazyFrame
        The annotation table.
    cell_id_col : str
        Column in ``lf`` holding the cell id to join on.
    join_on_alias : str or None
        If None, joins on the table's root-ID columns (``pre_col`` / ``post_col``).
        Otherwise names a registered cell alias.
    data_cols : list[str]
        Columns in ``lf`` (excluding the join key) that become
        ``_pre`` / ``_post`` columns on ``.df``.
    position_col : str or None
        Name of the data column (within ``data_cols``) that carries the cell's
        position as a struct with ``x`` / ``y`` / ``z`` fields. Declaring this
        role lets spatial filters (``filter_by_soma_distance``,
        ``filter_by_bbox``) locate the position without explicit per-call args.
        ``None`` means this annotation does not carry positions.
    is_universe : bool
        If True, this annotation's key set defines the authoritative cell
        universe — including cells with zero connections. Statistics that need
        a denominator (e.g. connection_probability) read membership from the
        universe annotation; null-model shufflers enumerate possible partners
        from it. See ``project_cell_annotation_as_universe.md``.

        A future ``Universe`` class will subsume this role; the flag is the
        migration anchor.
    """

    lf: pl.LazyFrame
    cell_id_col: str
    join_on_alias: str | None
    data_cols: list[str]
    position_col: str | None = None
    is_universe: bool = False


@dataclass
class VertexAnnotationSpec:
    """Vertex-level annotation: keyed on a supervoxel / vertex id, joined per side.

    Parameters
    ----------
    lf : pl.LazyFrame
        The annotation table.
    vertex_id_col : str
        Column in ``lf`` holding the vertex id to join on.
    pre_vertex_col : str or None
        Column on the base synapse table holding pre-side vertex ids.
        If given, annotation data columns appear as ``{col}_pre``.
    post_vertex_col : str or None
        Column on the base synapse table holding post-side vertex ids.
        If given, annotation data columns appear as ``{col}_post``.
    data_cols : list[str]
        Columns in ``lf`` (excluding the join key) that become
        ``_pre`` / ``_post`` columns on ``.df``.
    """

    lf: pl.LazyFrame
    vertex_id_col: str
    pre_vertex_col: str | None
    post_vertex_col: str | None
    data_cols: list[str]


# Discriminated union used by ``_AnnotationProxy`` and any generic helpers.
AnnotationSpec = Union[SynapseAnnotationSpec, CellAnnotationSpec, VertexAnnotationSpec]


# ── blessed columns ───────────────────────────────────────────────────────────


@dataclass
class BlessedColumns:
    """The semantically-meaningful columns the library owns for a given table.

    Trajan interprets only columns that are either (a) role-declared via one of
    the fields below, or (b) generated by trajan itself in a trajan-controlled
    namespace. Everything else in the table is user data with no library
    interpretation (see ``project_unified_blessed_columns.md``).

    Identifier roles (left empty when not applicable to this tier):

    - ``id_col`` — synapse id
    - ``pre_col`` / ``post_col`` — pre / post cell (or entity) id columns
    - ``pre_vertex_col`` / ``post_vertex_col`` — optional pre/post vertex id columns

    Value-type roles:

    - ``position_col`` — synapse position struct (``x`` / ``y`` / ``z``)
    - ``weights`` — columns carrying the weight contract (must-aggregate,
      default-sum, log-scale-compatible). ``n_syn`` appears here after
      aggregation to EdgeList / ConnectivityTable; user-registered weights
      (``size``, ``cleft_area``, etc.) live alongside it with no distinction.

    Notes
    -----
    On ``SynapseTable`` the ``pre_col`` / ``post_col`` fields hold cell-id
    columns; on EdgeList / ConnectivityTable they hold entity-id columns
    (cell for EdgeList, cell or label for ConnectivityTable). The role is
    the same — "the pre-side row index column" — but the semantic type
    differs by tier.
    """

    pre_col: str | None = None
    post_col: str | None = None
    id_col: str | None = None
    position_col: str | None = None
    pre_vertex_col: str | None = None
    post_vertex_col: str | None = None
    weights: list[str] = field(default_factory=list)


# ── input-coercion helpers ────────────────────────────────────────────────────


def _to_lazy(df) -> pl.LazyFrame:
    """Accept pl.DataFrame, pl.LazyFrame, or pd.DataFrame and return a LazyFrame."""
    if isinstance(df, pl.LazyFrame):
        return df
    if isinstance(df, pl.DataFrame):
        return df.lazy()
    if _HAS_PANDAS and isinstance(df, pd.DataFrame):
        return pl.from_pandas(df).lazy()
    raise TypeError(
        f"Expected pl.DataFrame, pl.LazyFrame, or pd.DataFrame, got {type(df)}"
    )


def _auto_pack(lf: pl.LazyFrame, col: str | None) -> pl.LazyFrame:
    """Pack ``{col}_x/y/z`` into a struct ``col`` if the struct is absent but
    the triplet exists. No-op if ``col`` is ``None`` or already present.
    """
    if col is None:
        return lf
    names = lf.collect_schema().names()
    if col in names:
        return lf
    if all(f"{col}_{ax}" in names for ax in ("x", "y", "z")):
        return pack_position(lf, col)
    return lf


# ── DataFolio helpers ─────────────────────────────────────────────────────────


def _as_folio(folio):
    """Return ``folio`` unchanged if it's already a DataFolio; otherwise open
    a DataFolio at the given path. Accepts ``str``, ``Path``, or DataFolio."""
    if isinstance(folio, (str, Path)):
        from datafolio import DataFolio

        return DataFolio(folio)
    return folio
